# Generated by Django 6.0.3 on 2026-03-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_booking_start_time_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10),
        ),
    ]
