# Generated by Django 6.0.3 on 2026-03-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_supportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
